# Generated by Django 5.2.3 on 2025-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='features',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tech',
        ),
    ]
